name: Build and Push Docker Image

on:
  push:
    branches:
      - main  # Dispara sempre que houver commit no main

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write # Essencial para o GITHUB_TOKEN ter permissÃ£o de escrita

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ github.repository }}
          tags: |
            type=raw,value=latest
            type=sha,format=short 

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
      - name: Trigger Webhook
        run: |
          curl -X GET -H "Content-Type: application/json" \
          https://easypanel.adfast.com.br/api/deploy/27b0d362e8ce92b1bc7b85fe31a5b634f73d02259729b6c5